### PR TITLE
Wiki issue 189

### LINKED ISSUE #189: Update wiki to reflect update to MySQL 8.0
**Is your feature request related to a problem? Please describe.**
The change to MySQL in issue https://github.com/aau-giraf/giraf-production-swarm/issues/10 and PR https://github.com/aau-giraf/giraf-production-swarm/pull/11 is not reflected in the wiki

**Describe the solution you'd like**
Update the following pages to reflect the update to MySQL 8.0:
https://aau-giraf.github.io/wiki/development/server_administration/docker_swarm/Database/
image

https://aau-giraf.github.io/wiki/development/server_administration/docker_swarm/DockerSwarm/
image

Check other places to make sure nothing was missed

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by MarcusEggeStudent**
opdateret det der står i docker compose filen, så det rigtige nu bliver vist i wikien

### CODE REVIEW

**Comment by MarcusEggeStudent** [comment]
closes #189

**Review by mads-bo — COMMENTED** [review]
@aau-giraf/sw609f20 you have been assigned this. Here's your checklist.

Please use the following checklist:

**Code Documentation Only**

- [ ] It is documented which BLoCs/Screens the current class is related to
- [ ] The responsibility/functionality of the current class is explained. Also regarding the classes it is related to
- [ ] If any unusual decisions are introduced in the code, they reasoned about in the documentation
 
**Wiki Related**

- [ ] There are no dead links or references
- [ ] The markdown renders correctly in MkDocs
- [ ] The content is placed in the correct page/folder/section

You can run MkDocs locally by following [this guide](https://aau-giraf.github.io/wiki/writing_wiki/#running-locally)

**Review by mads-bo — COMMENTED** [review]
@aau-giraf/sw613f20 you have been assigned this. Here's your checklist.

Please use the following checklist:

**Code Documentation Only**

- [ ] It is documented which BLoCs/Screens the current class is related to
- [ ] The responsibility/functionality of the current class is explained. Also regarding the classes it is related to
- [ ] If any unusual decisions are introduced in the code, they reasoned about in the documentation
 
**Wiki Related**

- [ ] There are no dead links or references
- [ ] The markdown renders correctly in MkDocs
- [ ] The content is placed in the correct page/folder/section

You can run MkDocs locally by following [this guide](https://aau-giraf.github.io/wiki/writing_wiki/#running-locally)

**Review by Lortemanden — DISMISSED** [review]

**Review by nicolaibjerring — DISMISSED** [review]

**Comment by MarcusEggeStudent** [comment]
When i solved a merge confligt i accidentally deleted one linebreak, and therefor now needs reapproveing ... sorry

**Review by Lortemanden — APPROVED** [review]

**Review by nicolaibjerring — APPROVED** [review]

**Pull request merged**
