### PR TITLE
Fixes 168

### PR DESCRIPTION
**Pull request by Semicolon1071**
Issue #168 required for a processing activity record to be written for the GIRAF project and related information is presented in an accompanying document.

### CODE REVIEW

**Review by mads-bo — COMMENTED** [review]
@aau-giraf/sw610f20 you have been assigned this. Here's your checklist.

Please use the following checklist:

**Code Documentation Only**

- [ ] It is documented which BLoCs/Screens the current class is related to
- [ ] The responsibility/functionality of the current class is explained. Also regarding the classes it is related to
- [ ] If any unusual decisions are introduced in the code, they reasoned about in the documentation
 
**Wiki Related**

- [x] There are no dead links or references
- [x] The markdown renders correctly in MkDocs
- [x] The content is placed in the correct page/folder/section

You can run MkDocs locally by following [this guide](https://aau-giraf.github.io/wiki/writing_wiki/#running-locally)

**Review by mads-bo — COMMENTED** [review]
@aau-giraf/sw613f20 you have been assigned this. Here's your checklist.

Please use the following checklist:

**Code Documentation Only**

- [ ] It is documented which BLoCs/Screens the current class is related to
- [ ] The responsibility/functionality of the current class is explained. Also regarding the classes it is related to
- [ ] If any unusual decisions are introduced in the code, they reasoned about in the documentation
 
**Wiki Related**

- [ ] There are no dead links or references
- [ ] The markdown renders correctly in MkDocs
- [ ] The content is placed in the correct page/folder/section

You can run MkDocs locally by following [this guide](https://aau-giraf.github.io/wiki/writing_wiki/#running-locally)

**Review by Lortemanden — CHANGES_REQUESTED** [review]
In the Processing Activity Record the description of a department is lacking. 

Did you get this Processing Activity Record from datatilsynet cause I find it kinda confusing to read?

**Comment by Torpstitution** [comment]
Yes, the Processing Activity Record itself is a template provided by Datatilsynet. This is why it looks the way it does, and we thought that it would be most wise to follow this structure.
Section 6. 
https://www.datatilsynet.dk/media/6567/fortegnelse.pdf

**Review by mathiasandresen — APPROVED** [review]

**Review by Lortemanden — APPROVED** [review]

**Pull request merged**
